alias tf="terraform"
alias tfe="tfenv"

alias tfv="tf validate"
alias tfp="tf plan"
alias tfpo="tf plan -out tfplan"
alias tfpd="tf plan -destroy"
alias tfa="tf apply"
alias tfu="tf apply -auto-approve"
alias tfd="tf destroy"

alias tfs="tf state"
alias tfsl="tf state list"
alias tfss="tf state show"
alias tfo="tf output"
alias tfw="tf workspace"